### PR TITLE
Feature/configurable ssh agent socket

### PR DESCRIPTION
**Pull request by mathpl**
Addition for configurable ssh-agent socket path and a small class to manage a ssh-agent instance.

### CODE REVIEW

**Comment by mathpl** [comment]
Can you give me some feedback on this? I'm hoping to get this feature in for another pull request in another project. Thanks!

**Comment by ymnk** [comment]
Commits should be squashed, and the request for SSHAgentProcess should be proposed in the other issue entry. 
The branch usocket_path 7ec35f75131ff626d714807d668da6649f0ca32c has introduced ConnectorFactory#setPreferredUSocketPath(String usocketPath) .

**Comment by mathpl** [comment]
Didn't notice you wrote in the feature (in a better way at that!). Thanks! Any way you could make a release with this branch merged?

**Comment by ymnk** [comment]
Please note the following methods
- setPreferredUSocketPath(String usocketPath),
- getPreferredUSocketPath()

have been renamed as
- setUSocketPath(String usocketPath)
- getUSocketPath() .

**Pull request closed without merging**
